module.exports = [
  {
    group: 'added',
    label: 'Added',
    emojis: [
      'sparkles',
      'tada',
      'white_check_mark',
      'construction_worker',
      'chart_with_upwards_trend',
      'heavy_plus_sign',
      'loud_sound',
      'package',
    ],
  },
  {
    group: 'changed',
    label: 'Changed',
    emojis: [
      'art',
      'zap',
      'lipstick',
      'rotating_light',
      'arrow_down',
      'arrow_up',
      'pushpin',
      'recycle',
      'wrench',
      'rewind',
      'alien',
      'truck',
      'bento',
      'wheelchair',
      'speech_balloon',
      'card_file_box',
      'children_crossing',
      'building_construction',
      'iphone',
    ],
  },
  {
    group: 'breaking_changes',
    label: 'Breaking changes',
    emojis: [
      'boom',
    ],
  },
  {
    group: 'deprecated',
    label: 'Deprecated',
    emojis: [
      'wastebasket',
    ],
  },
  {
    group: 'removed',
    label: 'Removed',
    emojis: [
      'fire',
      'heavy_minus_sign',
      'mute',
      'coffin',
    ],
  },
  {
    group: 'fixed',
    label: 'Fixed',
    emojis: [
      'bug',
      'ambulance',
      'green_heart',
      'adhesive_bandage',
      'pencil2',
    ],
  },
  {
    group: 'security',
    label: 'Security',
    emojis: ['lock', 'passport_control', 'see_no_evil'],
  },
  {
    group: 'useless',
    label: 'Useless',
    emojis: [
      'bookmark',
      'poop',
      'beers',
      'bulb',
      'twisted_rightwards_arrows',
    ],
  },
  {
    group: 'misc',
    label: 'Miscellaneous',
    emojis: [
      'clown_face',
      'bricks',
      'busts_in_silhouette',
    ],
  },
]
