const gitmojiMapping = {
  added: [
    'sparkles',
    'tada',
    'white_check_mark',
    'bookmark',
    'construction_worker',
    'charts_with_upwards_trend',
    'heavy_plus_sign',
    'loud_sound',
  ],
  changed: [
    'art',
    'zap',
    'lipstick',
    'rotating_light',
    'arrow_down',
    'arrow_up',
    'pushpin',
    'recycle',
    'wrench',
    'rewind',
    'alien',
    'truck',
    'boom',
    'bento',
    'wheelchair',
    'speech_ballon',
    'card_file_box',
    'children_crossing',
    'building_construction',
    'iphone',
  ],
  deprecated: [],
  removed: ['fire', 'heavy_minus_sign', 'mute'],
  fixed: [
    'bug',
    'ambulance',
    'apple',
    'penguin',
    'checkered_flag',
    'robot',
    'green_apple',
    'green_heart',
    'pencil2',
  ],
  security: ['lock'],
}

module.exports = gitmojiMapping
