module.exports = [
  {
    group: 'added',
    label: 'Added',
    emojis: [
      'sparkles',
      'tada',
      'white_check_mark',
      'bookmark',
      'construction_worker',
      'charts_with_upwards_trend',
      'heavy_plus_sign',
      'loud_sound',
    ],
  },
  {
    group: 'changed',
    label: 'Changed',
    emojis: [
      'art',
      'zap',
      'lipstick',
      'rotating_light',
      'arrow_down',
      'arrow_up',
      'pushpin',
      'recycle',
      'wrench',
      'rewind',
      'alien',
      'truck',
      'boom',
      'bento',
      'wheelchair',
      'speech_ballon',
      'card_file_box',
      'children_crossing',
      'building_construction',
      'iphone',
    ],
  },
  {
    group: 'deprecated',
    label: 'Deprecated',
    emojis: [],
  },
  {
    group: 'removed',
    label: 'Removed',
    emojis: ['fire', 'heavy_minus_sign', 'mute'],
  },
  {
    group: 'fixed',
    label: 'Fixed',
    emojis: [
      'bug',
      'ambulance',
      'apple',
      'penguin',
      'checkered_flag',
      'robot',
      'green_apple',
      'green_heart',
      'pencil2',
    ],
  },
  {
    group: 'security',
    label: 'Security',
    emojis: ['lock'],
  },
  {
    group: 'misc',
    label: 'Miscellaneous',
    emojis: [],
  },
]
